org.gradle.jvmargs=-Xmx8G -XX:MaxMetaspaceSize=4G -XX:ReservedCodeCacheSize=512m -XX:+HeapDumpOnOutOfMemoryError
android.useAndroidX=true

# 代理配置（如果您使用代理软件，请取消注释并修改端口）
systemProp.http.proxyHost=127.0.0.1
systemProp.http.proxyPort=4780
systemProp.https.proxyHost=127.0.0.1
systemProp.https.proxyPort=4780
# systemProp.http.nonProxyHosts=localhost|127.0.0.1

# 使用国内镜像源
org.gradle.parallel=true
org.gradle.daemon=true
org.gradle.configureondemand=true
